/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Fichajes;

import Controlador.Ctrl_Fichajes;
import Modelo.Empleado;
import Modelo.Fichaje;
import Vista.VPrincipal;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class VFichajes extends javax.swing.JDialog {

    Ctrl_Fichajes controlador = new Ctrl_Fichajes(VPrincipal.controladorBD.getConexion());

    public static String idFichaje, dni, fechaIni, fechaFin;

    /**
     * Creates new form VFichajes
     */
    public VFichajes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Icon/fichaje.png")).getImage());
        rellenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tFichajes = new javax.swing.JTable();
        bCrear = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Fichajes");

        tFichajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Fichaje", "DNI", "Hora de Inicio", "Hora de Fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tFichajes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tFichajes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tFichajes);
        if (tFichajes.getColumnModel().getColumnCount() > 0) {
            tFichajes.getColumnModel().getColumn(0).setResizable(false);
            tFichajes.getColumnModel().getColumn(1).setResizable(false);
            tFichajes.getColumnModel().getColumn(2).setResizable(false);
            tFichajes.getColumnModel().getColumn(3).setResizable(false);
        }

        bCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/crear.png"))); // NOI18N
        bCrear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        bBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/borrar.png"))); // NOI18N
        bBorrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        bModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/modificar.png"))); // NOI18N
        bModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(bCrear)
                .addGap(25, 25, 25)
                .addComponent(bBorrar)
                .addGap(25, 25, 25)
                .addComponent(bModificar)
                .addContainerGap(437, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCrear)
                    .addComponent(bBorrar)
                    .addComponent(bModificar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        VCrearFichaje v = new VCrearFichaje(null, true);
        v.setVisible(true);
        rellenarTabla();
    }//GEN-LAST:event_bCrearActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        if (tFichajes.getSelectedRow() != -1) {
            Object idFichaje1 = tFichajes.getValueAt(tFichajes.getSelectedRow(), 0);
            if (controlador.deleteFichaje(Integer.parseInt(idFichaje1.toString()))) {
                JOptionPane.showMessageDialog(this, "El fichaje " + idFichaje1.toString() + " ha sido eliminado correctamente");
                rellenarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "Error al borrar el fichaje", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un registro para borrarlo", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        if (tFichajes.getSelectedRow() != -1) {
            idFichaje = tFichajes.getValueAt(tFichajes.getSelectedRow(), 0).toString();
            dni = tFichajes.getValueAt(tFichajes.getSelectedRow(), 1).toString();
            fechaIni = tFichajes.getValueAt(tFichajes.getSelectedRow(), 2).toString();
            fechaFin = tFichajes.getValueAt(tFichajes.getSelectedRow(), 3).toString();
            VModificarFichaje v = new VModificarFichaje(null, true);
            v.setVisible(true);
            rellenarTabla();
        } else {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Seleccione un registro para modificarlo", "Error", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_bModificarActionPerformed

    public void rellenarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tFichajes.getModel();
        modelo.setRowCount(0);
        ArrayList<Fichaje> lista = controlador.devolverFichajes();
        for (Fichaje f : lista) {
            DateFormat formato = new SimpleDateFormat("dd/MM/yyyy H:mm");
            String fechaAux = formato.format(f.getFecHoraIni());
            String fechaAux2 = "(null)";
            if (f.getFecHoraFin() != null) {
                fechaAux2 = formato.format(f.getFecHoraFin());
            }
            modelo.addRow(new Object[]{f.getIdFichaje(), f.getDni(), fechaAux, fechaAux2});
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VFichajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VFichajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VFichajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VFichajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VFichajes dialog = new VFichajes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bCrear;
    private javax.swing.JButton bModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tFichajes;
    // End of variables declaration//GEN-END:variables
}
