/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Fichajes;

import Controlador.Ctrl_Fichajes;
import Modelo.Fichaje;
import Vista.VPrincipal;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class VModificarFichaje extends javax.swing.JDialog {

    Ctrl_Fichajes con = new Ctrl_Fichajes(VPrincipal.controladorBD.getConexion());

    /**
     * Creates new form VModificarFichaje
     */
    public VModificarFichaje(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Icon/modificar.png")).getImage());
        etIdFichaje.setText(VFichajes.idFichaje);
        etDni.setText(VFichajes.dni);
        etFechaIni.setText(VFichajes.fechaIni.substring(0, 10));
        etHoraIni.setText(VFichajes.fechaIni.substring(11, VFichajes.fechaIni.length()));
        if (VFichajes.fechaFin != "") {
            etFechaFin.setText(VFichajes.fechaFin.substring(0, 10));
            etHoraFin.setText(VFichajes.fechaFin.substring(11, VFichajes.fechaFin.length()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCrear = new javax.swing.JButton();
        etIdFichaje = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        etHoraIni = new javax.swing.JFormattedTextField();
        etHoraFin = new javax.swing.JFormattedTextField();
        etDni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        etFechaIni = new javax.swing.JFormattedTextField();
        etFechaFin = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Fichaje");

        bCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/modificar.png"))); // NOI18N
        bCrear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        etIdFichaje.setEnabled(false);
        etIdFichaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etIdFichajeKeyTyped(evt);
            }
        });

        jLabel1.setText("Id del Fichaje");

        jLabel2.setText("Dni");

        jLabel3.setText("Fecha y Hora de Inicio");

        etHoraIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        etHoraFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        etDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etDniKeyTyped(evt);
            }
        });

        jLabel4.setText("Fecha y Hora de Fin");

        etFechaIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        etFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etDni, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(etIdFichaje)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(etFechaFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(etFechaIni, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etHoraIni, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(etHoraFin))))
                .addGap(91, 91, 91))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bCrear)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etIdFichaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(etDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(etFechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(etFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bCrear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        if (!etIdFichaje.getText().isEmpty() && !etDni.getText().isEmpty() && !etFechaIni.getText().isEmpty() && !etHoraIni.getText().isEmpty()) {
            if (etFechaFin.getText().isEmpty() || etHoraFin.getText().isEmpty()) {
                Date fechaAux = null;
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy H:mm");
                try {
                    fechaAux = formato.parse(etFechaIni.getText() + " " + etHoraIni.getText());
                } catch (ParseException ex) {
                    System.out.println("ERROR : " + ex.getMessage());
                }
                java.sql.Timestamp timestamp = new java.sql.Timestamp(fechaAux.getTime());
                Fichaje f = new Fichaje(Integer.parseInt(etIdFichaje.getText()), etDni.getText(), timestamp);
                if (con.updateFichaje(f)) {
                    JOptionPane.showMessageDialog(this, "Fichaje modificado correctamente sin hora de Fin");
                } else {
                    getToolkit().beep();
                    JOptionPane.showMessageDialog(this, "Error al modificar el fichaje, comprueba que el dni este registrado", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                Date fechaAux = null;
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy H:mm");
                try {
                    fechaAux = formato.parse(etFechaIni.getText() + " " + etHoraIni.getText());
                } catch (ParseException ex) {
                    System.out.println("ERROR : " + ex.getMessage());
                }
                java.sql.Timestamp timestamp = new java.sql.Timestamp(fechaAux.getTime());
                Date fechaAux2 = null;
                SimpleDateFormat formato2 = new SimpleDateFormat("dd/MM/yyyy H:mm");
                try {
                    fechaAux2 = formato.parse(etFechaFin.getText() + " " + etHoraFin.getText());
                } catch (ParseException ex) {
                    System.out.println("ERROR : " + ex.getMessage());
                }
                java.sql.Timestamp timestamp2 = new java.sql.Timestamp(fechaAux2.getTime());
                Fichaje f = new Fichaje(Integer.parseInt(etIdFichaje.getText()), etDni.getText(), timestamp, timestamp2);
                if (con.updateFichaje(f)) {
                    JOptionPane.showMessageDialog(this, "Fichaje modificado correctamente");
                } else {
                    getToolkit().beep();
                    JOptionPane.showMessageDialog(this, "Error al modificar el fichaje, comprueba que el dni este registrado", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Los campos dni y fecha de inicio son obligatorios", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bCrearActionPerformed

    private void etIdFichajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etIdFichajeKeyTyped
        char car = evt.getKeyChar();
        if (!Character.isDigit(car) && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
        } else if (etIdFichaje.getText().length() == 10) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_etIdFichajeKeyTyped

    private void etDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etDniKeyTyped
        char car = evt.getKeyChar();
        if (evt.getKeyChar() != KeyEvent.VK_BACK_SPACE && !Character.isDigit(car) && !Character.isAlphabetic(car)) {
            evt.consume();
            getToolkit().beep();
        } else if (etDni.getText().length() == 10) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_etDniKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VModificarFichaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VModificarFichaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VModificarFichaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VModificarFichaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VModificarFichaje dialog = new VModificarFichaje(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCrear;
    private javax.swing.JTextField etDni;
    private javax.swing.JFormattedTextField etFechaFin;
    private javax.swing.JFormattedTextField etFechaIni;
    private javax.swing.JFormattedTextField etHoraFin;
    private javax.swing.JFormattedTextField etHoraIni;
    private javax.swing.JTextField etIdFichaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
