/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Empleados;

import Controlador.Ctrl_Empleados;
import Modelo.Empleado;
import Vista.VPrincipal;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class VCrearEmpleado extends javax.swing.JDialog {
    Ctrl_Empleados con = new Ctrl_Empleados(VPrincipal.controladorBD.getConexion());
    
    /**
     * Creates new form VCrearEmpleado
     */
    public VCrearEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Icon/crear.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etDni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        etNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        etHorasMin = new javax.swing.JFormattedTextField();
        etPrecioHoras = new javax.swing.JFormattedTextField();
        etPrecioHorasEx = new javax.swing.JFormattedTextField();
        bCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Empleado");
        setResizable(false);

        etDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etDniKeyTyped(evt);
            }
        });

        jLabel1.setText("DNI");

        jLabel2.setText("Nombre");

        jLabel3.setText("Horas Mínimas");

        etNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etNombreKeyTyped(evt);
            }
        });

        jLabel4.setText("Precio Horas");

        jLabel5.setText("Precio Horas Extras");

        etHorasMin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        etHorasMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etHorasMinKeyTyped(evt);
            }
        });

        etPrecioHoras.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        etPrecioHoras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etPrecioHorasKeyTyped(evt);
            }
        });

        etPrecioHorasEx.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        etPrecioHorasEx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etPrecioHorasExKeyTyped(evt);
            }
        });

        bCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/crear.png"))); // NOI18N
        bCrear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etHorasMin)
                    .addComponent(etNombre)
                    .addComponent(etPrecioHorasEx, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etPrecioHoras)
                    .addComponent(etDni))
                .addGap(91, 91, 91))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bCrear)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(etNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(etHorasMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(etPrecioHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(etPrecioHorasEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCrear)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etDniKeyTyped
        char car = evt.getKeyChar();
        if (!Character.isDigit(car) && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE && !Character.isAlphabetic(car)) {
            if (etDni.getText().length() == 10) {
                evt.consume();
                getToolkit().beep();
            }
        }
    }//GEN-LAST:event_etDniKeyTyped

    private void etNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etNombreKeyTyped
        char car = evt.getKeyChar();
        if (evt.getKeyChar() != KeyEvent.VK_BACK_SPACE && !Character.isAlphabetic(car)) {
            if (etNombre.getText().length() == 100) {
                evt.consume();
                getToolkit().beep();
            }
        }
    }//GEN-LAST:event_etNombreKeyTyped

    private void etHorasMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etHorasMinKeyTyped
        char num = evt.getKeyChar();
        if (!Character.isDigit(num) && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE && evt.getKeyChar() != KeyEvent.VK_COMMA) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_etHorasMinKeyTyped

    private void etPrecioHorasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etPrecioHorasKeyTyped
        char num = evt.getKeyChar();
        if (!Character.isDigit(num) && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE && evt.getKeyChar() != KeyEvent.VK_COMMA) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_etPrecioHorasKeyTyped

    private void etPrecioHorasExKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etPrecioHorasExKeyTyped
        char num = evt.getKeyChar();
        if (!Character.isDigit(num) && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE && evt.getKeyChar() != KeyEvent.VK_COMMA) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_etPrecioHorasExKeyTyped

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        if(!etDni.getText().isEmpty()&&!etNombre.getText().isEmpty()){
            if(etHorasMin.getText().isEmpty()&&etPrecioHoras.getText().isEmpty()&&etPrecioHorasEx.getText().isEmpty()){
                if(!con.insertEmpleado(new Empleado(etDni.getText(),etNombre.getText()))){
                    JOptionPane.showMessageDialog(this, "El empleado con dni "+etDni.getText()+" no ha podido ser añadido","Error",JOptionPane.ERROR_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, "Alta correcta");
                    etDni.setText("");
                    etNombre.setText("");
                    etHorasMin.setText("");
                    etPrecioHoras.setText("");
                    etPrecioHorasEx.setText("");
                }
            }else if(etPrecioHorasEx.getText().isEmpty()){
                if(!con.insertEmpleado(new Empleado(etDni.getText(),etNombre.getText(), Double.parseDouble(etHorasMin.getText().replace(",",".")), Double.parseDouble(etPrecioHoras.getText().replace(",","."))))){
                    JOptionPane.showMessageDialog(this, "El empleado con dni "+etDni.getText()+" no ha podido ser añadido","Error",JOptionPane.ERROR_MESSAGE);                    
                }else{
                    JOptionPane.showMessageDialog(this, "Alta correcta");
                    etDni.setText("");
                    etNombre.setText("");
                    etHorasMin.setText("");
                    etPrecioHoras.setText("");
                    etPrecioHorasEx.setText("");
                }
            }else{
                if(!con.insertEmpleado(new Empleado(etDni.getText(),etNombre.getText(), Double.parseDouble(etHorasMin.getText().replace(",",".")), Double.parseDouble(etPrecioHoras.getText().replace(",",".")),Double.parseDouble(etPrecioHorasEx.getText().replace(",","."))))){
                    JOptionPane.showMessageDialog(this, "El empleado con dni "+etDni.getText()+" no ha podido ser añadido","Error",JOptionPane.ERROR_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, "Alta correcta");
                    etDni.setText("");
                    etNombre.setText("");
                    etHorasMin.setText("");
                    etPrecioHoras.setText("");
                    etPrecioHorasEx.setText("");
                }
            }
        }
    }//GEN-LAST:event_bCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCrearEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCrearEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCrearEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCrearEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VCrearEmpleado dialog = new VCrearEmpleado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCrear;
    private javax.swing.JTextField etDni;
    private javax.swing.JFormattedTextField etHorasMin;
    private javax.swing.JTextField etNombre;
    private javax.swing.JFormattedTextField etPrecioHoras;
    private javax.swing.JFormattedTextField etPrecioHorasEx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
